/* SPDX-License-Identifier: MIT */

#include "chickens.h"
#include "cpu_regs.h"
#include "utils.h"

void init_t8030_lightning(int rev)
{
    (void)rev;
    reg_set(SYS_IMP_APL_HID5, HID5_DISABLE_FILL_2C_MERGE);
    reg_set(SYS_IMP_APL_HID0, HID0_CACHE_FUSION_DISABLE);
    reg_mask(SYS_IMP_APL_HID4, HID4_CNF_CNTR_THRESH_MASK, HID4_CNF_CNTR_THRESH(3));
    reg_set(SYS_IMP_APL_HID9, HID9_FIX_BUG_47221499);
    reg_set(SYS_IMP_APL_HID9, HID9_DISABLE_NT_WIDGET_FOR_UNALIGNED);
    reg_set(SYS_IMP_APL_HID16, HID16_ENABLE_RS4_SEC);
    reg_clr(SYS_IMP_APL_HID16, HID16_DISABLE_X_PICK_RS45);
    reg_set(SYS_IMP_APL_HID16, HID16_ENABLE_MPX_PICK_45);
    reg_set(SYS_IMP_APL_HID16, HID16_ENABLE_MP_CYCLONE_7);
    reg_set(SYS_IMP_APL_HID4, HID4_FORCE_NS_ORD_LD_REQ_NO_OLDER_LD);
    reg_set(SYS_IMP_APL_HID4, HID4_DISABLE_STNT_WIDGET);
    reg_set(SYS_IMP_APL_HID11, HID11_DISABLE_X64_NT_LAUNCH_OPTION);
    reg_set(SYS_IMP_APL_HID16, HID16_ENABLE_AGGRESSIVE_LEQ_THROTTLING);
    reg_mask(SYS_IMP_APL_HID13, HID13_PRE_CYCLES_MASK, HID13_PRE_CYCLES(4));
}
